apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: omc-app
    app.kubernetes.io/component: omc-app
    app.kubernetes.io/instance: omc-app
  name: openshift-mini-console-sa-clusterrolebinding
  namespace: omc-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-mini-console-sa-clusterrole
subjects:
  - kind: ServiceAccount
    name: openshift-mini-console-sa
    namespace: omc-app
