apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: omc-app
    app.kubernetes.io/component: omc-app
    app.kubernetes.io/instance: omc-app
  name: openshift-mini-console-sa-clusterrole
  namespace: omc-app
rules:
  - apiGroups:
      - "*"
    resources:
      - clusterversions
      - infrastructures
      - infrastructures
      - machinesets
      - nodes
      - routes
    verbs:
      - get
      - list
      - watch
