apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kustomize-deploy
  namespace: omc-app
spec:
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "deploy/kustomize"
  steps:
    - name: apply
      image: registry.redhat.io/openshift4/ose-cli
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          oc apply -k $(inputs.params.manifest_dir)
          echo -----------------------------------
